apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:  
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-mongodb
spec:      
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Release.Name }}-mongodb
  strategy: {}
  template:
    metadata:
      labels:
        deployment: {{ .Release.Name }}-mongodb
    spec:  
      containers:
      - image: {{ .Values.mongodb.image }}
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: mongodbUser
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: mongodbPassword
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: mongodbDatabase
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: mongodbAdminPassword
        - name: MONGODB_QUIET
          value: {{ .Values.mongodb.quiet | quote }}
        imagePullPolicy: {{ .Values.mongodb.imagePullPolicy }}
        name: {{ .Release.Name }}-mongodb
        ports:
        - containerPort: {{ .Values.mongodb.port }}
          protocol: TCP
        securityContext:
          capabilities: {}
          privileged: false
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mongodb/data
          name: {{ .Release.Name }}-mongodb-data
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: {{ .Release.Name }}-mongodb-data
