apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
    protocol: TCP
  selector:
    deployment: {{ .Release.Name }}-mongodb
