{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - {{ .Values.ingress.hostname }}
  gateways:
  - {{ .Release.Name }}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.wildfly.port }}
{{- end }}
